# Generated by Django 3.0.1 on 2020-01-22 18:07

from django.db import migrations
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='picture55',
            field=django_resized.forms.ResizedImageField(blank=True, crop=['middle', 'center'], default='profile_pictures/default.png', force_format=None, keep_meta=True, quality=0, size=[55, 55], upload_to='profile_pictures'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='picture',
            field=django_resized.forms.ResizedImageField(blank=True, crop=['middle', 'center'], default='profile_pictures/default.png', force_format=None, keep_meta=True, quality=0, size=[150, 150], upload_to='profile_pictures'),
        ),
    ]
