# Generated by Django 3.0.1 on 2019-12-30 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20191230_2051'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('Landlord', 1), ('Tenant', 2)], max_length=10),
        ),
    ]
