# Generated by Django 3.0.1 on 2020-01-01 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_auto_20191230_2304'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('Landlord', 'Landlord'), ('Tenant', 'Tenant')], max_length=10),
        ),
    ]
