# Generated by Django 3.0.1 on 2020-01-02 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_auto_20200102_2103'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='picture',
            field=models.ImageField(blank=True, default='profile_pictures/default.png', upload_to='profile_pictures'),
        ),
    ]
