# Generated by Django 3.0.1 on 2020-01-22 15:19

from django.db import migrations
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0009_auto_20200102_2134'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='picture',
            field=django_resized.forms.ResizedImageField(blank=True, crop=['middle', 'center'], default='profile_pictures/default.png', force_format=None, keep_meta=True, quality=0, size=[200, 200], upload_to='profile_pictures'),
        ),
    ]
