# Generated by Django 3.0.1 on 2020-01-22 09:27

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('address', models.CharField(blank=True, max_length=255)),
                ('deposit', models.FloatField()),
                ('price', models.FloatField()),
                ('thumbnail', models.ImageField(default='property_thumbnails/default.png', upload_to='property_thumbnails')),
                ('tagline', models.CharField(max_length=40, null=True)),
                ('description', models.TextField(blank=True)),
                ('property_type', models.CharField(blank=True, max_length=30)),
                ('capacity', models.IntegerField()),
                ('bathroom', models.IntegerField(default=0)),
                ('is_furnished', models.BooleanField(default=False)),
                ('is_pets_allowed', models.BooleanField(default=False)),
                ('is_laundry', models.BooleanField(default=False)),
                ('is_parking', models.BooleanField(default=False)),
                ('is_storage', models.BooleanField(default=False)),
                ('is_air_conditioned', models.BooleanField(default=False)),
                ('is_ceiling_fans', models.BooleanField(default=False)),
                ('is_sink', models.BooleanField(default=False)),
                ('is_garbage_disposal', models.BooleanField(default=False)),
                ('is_hardwood_floors', models.BooleanField(default=False)),
                ('is_internet', models.BooleanField(default=False)),
                ('is_microwave', models.BooleanField(default=False)),
                ('is_refrigerator', models.BooleanField(default=False)),
                ('is_stove', models.BooleanField(default=False)),
                ('is_telephone', models.BooleanField(default=False)),
                ('is_tile', models.BooleanField(default=False)),
                ('is_window_covering', models.BooleanField(default=False)),
                ('is_elevator', models.BooleanField(default=False)),
                ('terms_of_agreement', models.TextField(blank=True)),
                ('views', models.IntegerField(null=True)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('favorite', models.ManyToManyField(blank=True, related_name='favorite', to=settings.AUTH_USER_MODEL, verbose_name='users that likes the property')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Reminder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=30)),
                ('sub_category', models.CharField(blank=True, max_length=30)),
                ('issue', models.CharField(blank=True, max_length=80)),
                ('next_service', models.DateField(default=datetime.date.today, verbose_name='Date')),
                ('description', models.TextField(blank=True)),
                ('property_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='landlord.Property')),
            ],
        ),
        migrations.CreateModel(
            name='AddTenant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_user', models.EmailField(default='defatult@gmail.com', max_length=60)),
                ('room_description', models.CharField(max_length=80)),
                ('balance', models.IntegerField(null=True)),
                ('is_paid', models.BooleanField(default=False)),
                ('date_paid', models.DateField(default=datetime.date(2020, 1, 22))),
                ('account', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('dorm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='landlord.Property')),
            ],
        ),
    ]
