# Generated by Django 3.0.1 on 2020-01-23 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landlord', '0003_auto_20200123_0207'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addtenant',
            name='balance',
            field=models.IntegerField(default=0),
        ),
    ]
