# Generated by Django 3.0.1 on 2020-02-24 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landlord', '0013_auto_20200224_2002'),
    ]

    operations = [
        migrations.AddField(
            model_name='addtenant',
            name='is_bedspace',
            field=models.CharField(default='Bedspace', max_length=80),
        ),
    ]
