# Generated by Django 3.0.1 on 2020-02-24 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landlord', '0014_addtenant_is_bedspace'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='addtenant',
            name='is_bedspace',
        ),
        migrations.AddField(
            model_name='addtenant',
            name='is_inclusive',
            field=models.CharField(default='Inclusive', max_length=80),
        ),
    ]
