# Generated by Django 3.0.1 on 2020-03-09 04:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('landlord', '0017_addtenant_wallet'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='expenses',
            name='date',
        ),
    ]
