# Generated by Django 3.0.1 on 2020-01-03 14:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('address', models.TextField()),
                ('capacity', models.IntegerField()),
                ('deposit', models.IntegerField()),
                ('price', models.IntegerField()),
                ('thumbnail', models.ImageField(default='property_thumbnails/default.png', upload_to='property_thumbnails')),
                ('latitude', models.FloatField()),
                ('longitued', models.FloatField()),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
