# Generated by Django 3.0.1 on 2020-01-22 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landlord', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addtenant',
            name='date_paid',
            field=models.DateField(null=True),
        ),
    ]
