# Generated by Django 3.0.1 on 2020-01-03 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landlord', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='property',
            old_name='longitued',
            new_name='longitude',
        ),
        migrations.AlterField(
            model_name='property',
            name='deposit',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='property',
            name='price',
            field=models.FloatField(),
        ),
    ]
