# Generated by Django 3.0.1 on 2020-01-22 18:07

from django.db import migrations, models
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('landlord', '0002_auto_20200122_1746'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='slots',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='property',
            name='thumbnail',
            field=django_resized.forms.ResizedImageField(blank=True, crop=['middle', 'center'], default='property_thumbnails/default.png', force_format=None, keep_meta=True, quality=0, size=[1000, 950], upload_to='property_thumbnails'),
        ),
        migrations.AlterField(
            model_name='property',
            name='views',
            field=models.IntegerField(default=0),
        ),
    ]
