# Generated by Django 3.0.1 on 2020-02-05 15:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landlord', '0005_auto_20200205_2152'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addtenant',
            name='date_paid',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
