# Generated by Django 3.0.1 on 2020-01-04 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landlord', '0005_auto_20200104_2245'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='house_number',
            field=models.IntegerField(null=True),
        ),
    ]
