# Generated by Django 3.0.1 on 2020-02-06 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landlord', '0006_auto_20200205_2350'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addtenant',
            name='is_paid',
            field=models.BooleanField(default=True),
        ),
    ]
