# Generated by Django 3.0.1 on 2020-01-05 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landlord', '0007_auto_20200105_1920'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='tagline',
            field=models.CharField(max_length=40, null=True),
        ),
    ]
