# Generated by Django 3.0.1 on 2020-01-05 13:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('landlord', '0009_property_activity_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='property',
            name='activity_type',
        ),
    ]
