# Generated by Django 3.0.1 on 2020-01-05 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landlord', '0011_property_favorite'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='property',
            name='favorite',
        ),
        migrations.AddField(
            model_name='property',
            name='is_favorite',
            field=models.BooleanField(default=False),
        ),
    ]
