# Generated by Django 3.0.1 on 2020-01-05 17:30

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('landlord', '0012_auto_20200106_0038'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='property',
            name='is_favorite',
        ),
        migrations.AddField(
            model_name='property',
            name='favorite',
            field=models.ManyToManyField(blank=True, related_name='favorite', to=settings.AUTH_USER_MODEL),
        ),
    ]
