# Generated by Django 3.0.1 on 2020-01-07 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landlord', '0013_auto_20200106_0130'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='property',
            name='favorite',
        ),
        migrations.AddField(
            model_name='property',
            name='is_favorite',
            field=models.BooleanField(default=False),
        ),
    ]
