# Generated by Django 3.0.1 on 2020-01-08 15:01

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('landlord', '0015_auto_20200107_1142'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='favorite',
            field=models.ManyToManyField(blank=True, related_name='favorite', to=settings.AUTH_USER_MODEL, verbose_name='users that likes the property'),
        ),
    ]
