# Generated by Django 3.0.1 on 2020-01-08 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landlord', '0016_auto_20200108_2301'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='bathroom',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='property',
            name='property_type',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
