# Generated by Django 3.0.1 on 2020-01-08 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landlord', '0017_auto_20200109_0102'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='terms_of_agreement',
            field=models.TextField(blank=True),
        ),
    ]
