# Generated by Django 3.0.1 on 2020-01-10 07:55

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('landlord', '0018_property_terms_of_agreement'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reminder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=30)),
                ('sub_category', models.CharField(blank=True, max_length=30)),
                ('issue', models.CharField(blank=True, max_length=30)),
                ('next_service', models.DateTimeField(default=django.utils.timezone.now)),
                ('days_before', models.DateTimeField(default=django.utils.timezone.now)),
                ('description', models.TextField(blank=True)),
                ('property_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='landlord.Property')),
            ],
        ),
    ]
