# Generated by Django 3.0.1 on 2020-01-10 10:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('landlord', '0019_reminder'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reminder',
            name='property_name',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='landlord.Property'),
        ),
    ]
