# Generated by Django 3.0.1 on 2020-01-10 11:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landlord', '0021_auto_20200110_1806'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reminder',
            name='days_before',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='reminder',
            name='issue',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AlterField(
            model_name='reminder',
            name='next_service',
            field=models.DateField(default=datetime.date.today, verbose_name='Date'),
        ),
    ]
