# Generated by Django 3.0.1 on 2020-01-13 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landlord', '0022_auto_20200110_1935'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='address',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
