# Generated by Django 3.0.1 on 2020-01-15 00:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('landlord', '0024_auto_20200113_2021'),
        ('landlord', '0024_auto_20200113_1924'),
    ]

    operations = [
    ]
