# Generated by Django 3.0.1 on 2020-01-22 03:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landlord', '0026_property_views'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reminder',
            name='days_before',
        ),
        migrations.AlterField(
            model_name='property',
            name='views',
            field=models.IntegerField(),
        ),
    ]
