# Generated by Django 3.0.1 on 2020-01-20 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landlord', '0026_property_views'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='views',
            field=models.IntegerField(),
        ),
    ]
