# Generated by Django 3.0.1 on 2020-01-21 01:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landlord', '0027_auto_20200120_1506'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='views',
            field=models.IntegerField(null=True),
        ),
    ]
