# Generated by Django 3.0.1 on 2020-01-22 04:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('landlord', '0027_auto_20200122_1113'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addtenant',
            name='account_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
