# Generated by Django 3.0.1 on 2020-01-22 04:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('landlord', '0029_auto_20200122_1235'),
    ]

    operations = [
        migrations.AddField(
            model_name='addtenant',
            name='account',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='addtenant',
            name='account_user',
            field=models.EmailField(default='defatult@gmail.com', max_length=60),
        ),
    ]
