# Generated by Django 3.0.1 on 2020-01-22 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landlord', '0030_auto_20200122_1244'),
    ]

    operations = [
        migrations.AddField(
            model_name='addtenant',
            name='date_paid',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='addtenant',
            name='is_paid',
            field=models.BooleanField(default=False),
        ),
    ]
