# Generated by Django 3.0.1 on 2020-01-22 09:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('landlord', '0032_addtenant_balance'),
        ('landlord', '0028_auto_20200121_0936'),
    ]

    operations = [
    ]
