# Generated by Django 3.0.1 on 2020-01-22 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landlord', '0034_property_slots'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='views',
            field=models.IntegerField(default=0),
        ),
    ]
