# Generated by Django 3.0.1 on 2020-01-22 15:50

from django.db import migrations
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('landlord', '0035_auto_20200122_1929'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='thumbnail',
            field=django_resized.forms.ResizedImageField(blank=True, crop=['middle', 'center'], default='property_thumbnails/default.png', force_format=None, keep_meta=True, quality=0, size=[1000, 950], upload_to='property_thumbnails'),
        ),
    ]
