# Generated by Django 3.0.1 on 2020-01-08 20:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('landlord', '0018_property_terms_of_agreement'),
        ('tenant', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='dorm',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='landlord.Property'),
        ),
    ]
