# Generated by Django 3.0.1 on 2020-02-19 08:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('landlord', '0007_auto_20200206_1607'),
        ('tenant', '0002_auto_20200205_2347'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messageroom',
            name='dorm',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='landlord.Property'),
        ),
    ]
