# Generated by Django 3.0.1 on 2020-01-08 21:04

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('landlord', '0018_property_terms_of_agreement'),
        ('tenant', '0002_application_dorm'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='application',
            name='dorm',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='landlord.Property'),
        ),
    ]
