# Generated by Django 3.0.1 on 2020-02-19 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenant', '0003_auto_20200219_1603'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messageroom',
            name='name',
            field=models.CharField(default='defaultRoom', max_length=30),
        ),
    ]
