# Generated by Django 3.0.1 on 2020-01-09 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenant', '0004_application_is_approved'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='is_disapproved',
            field=models.BooleanField(default=False),
        ),
    ]
