# Generated by Django 3.0.1 on 2020-01-15 01:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenant', '0005_application_is_disapproved'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='schedule',
            field=models.DateField(blank=True, null=True),
        ),
    ]
