# Generated by Django 3.0.1 on 2020-01-21 01:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('landlord', '0027_auto_20200120_1506'),
        ('tenant', '0008_messageroom'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='messageroom',
            name='host',
        ),
        migrations.RemoveField(
            model_name='messageroom',
            name='name',
        ),
        migrations.AddField(
            model_name='message',
            name='room',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tenant.MessageRoom'),
        ),
        migrations.AddField(
            model_name='messageroom',
            name='dorm',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='landlord.Property'),
        ),
    ]
