# Generated by Django 3.0.1 on 2020-01-21 01:09

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('tenant', '0009_auto_20200121_0904'),
    ]

    operations = [
        migrations.AddField(
            model_name='messageroom',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
