# Generated by Django 3.0.1 on 2020-01-21 01:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('landlord', '0028_auto_20200121_0936'),
        ('tenant', '0010_messageroom_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messageroom',
            name='dorm',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='landlord.Property'),
        ),
    ]
