# Generated by Django 3.0.1 on 2020-01-22 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenant', '0012_messageroom_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messageroom',
            name='name',
            field=models.CharField(default='defaultRoom', max_length=15),
        ),
    ]
